<a href="https://colab.research.google.com/github/phamducdai092/AI_lab/blob/main/Lab_6_21130304_PhamDucDai.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# This lab is to deal with classification task using **Random Forests** and **Na√Øve Bayes** algorithms with/without **Feature Selection**.

*   **Deadline: 23:59, 15/04/2024**

# Import libraries

In [2]:
# from google.colab import drive
# drive.mount('/content/gdrive')
%cd '/content/gdrive/MyDrive/ML/lab6'

/content/gdrive/MyDrive/ML/lab6

In [10]:
# code
import numpy as np
from sklearn.ensemble import BaggingClassifier
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.svm import SVC
import seaborn as sns
from sklearn.impute import SimpleImputer
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from prettytable import PrettyTable
from sklearn.feature_selection import chi2
from sklearn.feature_selection import SelectKBest
from sklearn import metrics
from sklearn import svm
from sklearn.preprocessing import LabelEncoder

#Task 1.
Task 1. Compare the performance of selected classification algorithms including **Random forest**, **NaiveBayes**, and **SVM** with **FASHION** dataset based on **accuracy, precision, recall, f1** measures according to **without using selection feature** and **using selection feature**.

In [42]:
# code
algo_array = {
    0: 'Random forest',
    1: 'Navie Bayes MultinomialNB',
    2: 'SVM linear',
    3: 'Decision tree',
    4: 'Logistic Regression',
    5: 'kNN k=5'
}


def getScore(algo, X_train, X_test, y_train, y_test):
  if(algo==0):
    clf = RandomForestClassifier();
  elif(algo==1):
    clf = MultinomialNB()
  elif(algo==2):
    clf = svm.SVC(kernel='linear')
  elif(algo==3):
    clf = DecisionTreeClassifier()
  elif(algo==4):
    clf = LogisticRegression(max_iter=50000)
  elif(algo==5):
    clf = KNeighborsClassifier();
  clf.fit(X_train, y_train.values.ravel())
  y_pred = clf.predict(X_test);
  accuracy = metrics.accuracy_score(y_test, y_pred)
  precision = metrics.precision_score(y_test, y_pred, average='macro')
  recall = metrics.recall_score(y_test, y_pred, average='macro')
  f1 = metrics.f1_score(y_test, y_pred, average='macro')
  algo_name = algo_array.get(algo)
  return [algo_name, accuracy, precision, recall, f1]

In [29]:
#code
fashion_data = pd.read_csv('fashion_train.csv')

X = fashion_data.drop(columns='y')
y = fashion_data[['y']]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# print table
print('not using selection feature')
table_not_using = PrettyTable(['Algorithms', 'Accuracy', 'Precision', 'Recall', 'F1'])
for i in range(0,3):
  table_not_using.add_row(getScore(i, X_train, X_test, y_train, y_test))
print(table_not_using)

new_X = SelectKBest(chi2, k=round(fashion_data.shape[1] / 2)).fit_transform(X, y)
X_train, X_test, y_train, y_test = train_test_split(new_X, y, test_size=0.2)
print('using selection feature')
table_using = PrettyTable(['Algorithms', 'Accuracy', 'Precision', 'Recall', 'F1'])
for i in range(0,3):
  table_using.add_row(getScore(i, X_train, X_test, y_train, y_test))
print(table_using)

not using selection feature
+---------------------------+----------+--------------------+--------------------+--------------------+
|         Algorithms        | Accuracy |     Precision      |       Recall       |         F1         |
+---------------------------+----------+--------------------+--------------------+--------------------+
|       Random forest       |  0.855   | 0.8443321667339705 | 0.8545380277617121 | 0.8469774544959229 |
| Navie Bayes MultinomialNB |   0.69   |  0.66842784992785  | 0.6754532967032967 | 0.639191814994273  |
|         SVM linear        |  0.795   | 0.7944322782480676 | 0.7876976094081357 | 0.7859434558625661 |
+---------------------------+----------+--------------------+--------------------+--------------------+
using selection feature
+---------------------------+----------+--------------------+--------------------+--------------------+
|         Algorithms        | Accuracy |     Precision      |       Recall       |         F1         |
+---------------------------+----------+--------------------+--------------------+--------------------+
|       Random forest       |   0.78   | 0.7852477152477153 | 0.7746855653307266 | 0.7769956697747402 |
| Navie Bayes MultinomialNB |   0.57   |  0.5435951758969   | 0.5850773867709351 | 0.5392370088136944 |
|         SVM linear        |   0.76   | 0.7792384808174282 | 0.7580689964157705 | 0.7596388007550897 |
+---------------------------+----------+--------------------+--------------------+--------------------+

#Task 2.
For given bank dataset (**bank.csv**) having the following attributes :
1.	**age** (numeric)
2.	**job** : type of job (categorical: 'admin.','blue-collar','entrepreneur','housemaid','management','retired','self-employed','services','student','technician','unemployed','unknown')
3.	**marital** : marital status (categorical: 'divorced','married','single','unknown'; note: 'divorced' means divorced or widowed)
4.	**education** (categorical: 'basic.4y','basic.6y','basic.9y','high.school','illiterate','professional.course','university.degree','unknown')
5.	**default**: has credit in default? (categorical: 'no','yes','unknown')
6.	**housing**: has housing loan? (categorical: 'no','yes','unknown')
7.	**loan**: has personal loan? (categorical: 'no','yes','unknown')
8.	**contact**: contact communication type (categorical: 'cellular','telephone')
9.	**month**: last contact month of year (categorical: 'jan', 'feb', 'mar', ..., 'nov', 'dec')
10.	**day_of_week**: last contact day of the week (categorical: 'mon','tue','wed','thu','fri')
11.	**duration**: last contact duration, in seconds (numeric). Important note: this attribute highly affects the output target (e.g., if duration=0 then y='no'). Yet, the duration is not known before a call is performed. Also, after the end of the call y is obviously known. Thus, this input should only be included for benchmark purposes and should be discarded if the intention is to have a realistic predictive model.
12.	**campaign**: number of contacts performed during this campaign and for this client (numeric, includes last contact)
13.	**pdays**: number of days that passed by after the client was last contacted from a previous campaign (numeric; 999 means client was not previously contacted)
14.	**previous**: number of contacts performed before this campaign and for this client (numeric)
15.	**poutcome**: outcome of the previous marketing campaign (categorical: 'failure','nonexistent','success')
Output variable (desired target):
16.	**y**. has the client subscribed a term deposit? (binary: 'yes','no')

#2.1. Apply StandardScaler() function to columns that contains numerical data ('age', 'balance', 'day', 'campaign', 'pdays', 'previous')

In [43]:
def my_scaler(data, columns):
  scaler = StandardScaler()
  for i in columns:
    data[[i]] = scaler.fit_transform(data[[i]])
    data[[i]] += abs(data[[i]].min())
  return data

In [44]:
#code
bank_data = pd.read_csv('bank.csv')
columns = ['age', 'balance', 'day', 'campaign', 'pdays', 'previous']
new_bank_data = my_scaler(bank_data, columns)
new_bank_data

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,3.441666,admin.,married,secondary,no,2.849375,yes,no,unknown,0.475039,may,1042,0.000000,0.000000,0.000000,unknown,yes
1,3.189837,admin.,married,secondary,no,2.136876,no,no,unknown,0.475039,may,1467,0.000000,0.000000,0.000000,unknown,yes
2,1.930691,technician,married,secondary,no,2.516689,yes,no,unknown,0.475039,may,1389,0.000000,0.000000,0.000000,unknown,yes
3,3.105894,services,married,secondary,no,2.890612,yes,no,unknown,0.475039,may,579,0.000000,0.000000,0.000000,unknown,yes
4,3.021951,admin.,married,tertiary,no,2.179973,no,no,unknown,0.475039,may,673,0.367383,0.000000,0.000000,unknown,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11157,1.259146,blue-collar,single,primary,no,2.123234,yes,no,cellular,2.256435,apr,257,0.000000,0.000000,0.000000,unknown,no
11158,1.762804,services,married,secondary,no,2.350192,no,no,unknown,1.781396,jun,83,1.102149,0.000000,0.000000,unknown,no
11159,1.175203,technician,single,secondary,no,2.131915,no,no,cellular,2.137675,aug,156,0.367383,0.000000,0.000000,unknown,no
11160,2.098577,technician,married,secondary,no,2.122924,no,yes,cellular,0.831318,may,9,0.367383,1.590755,2.181592,failure,no
11161,1.343089,technician,married,secondary,no,2.122924,no,no,cellular,0.950078,jul,628,0.000000,0.000000,0.000000,unknown,no

#2.2. Apply Encode Categorical Value (OneHotEncoder) to transfrom categorical data to numerical data ('job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome')

In [45]:
def my_label_encoder(data, columns):
  label_encoder = LabelEncoder()
  for i in columns:
    data[i] = label_encoder.fit_transform(data[i])
  return data

In [46]:
#code
columns = ['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome']
new_bank_data = my_label_encoder(bank_data, columns)
new_bank_data

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,3.441666,0,1,1,0,2.849375,1,0,2,0.475039,8,1042,0.000000,0.000000,0.000000,3,yes
1,3.189837,0,1,1,0,2.136876,0,0,2,0.475039,8,1467,0.000000,0.000000,0.000000,3,yes
2,1.930691,9,1,1,0,2.516689,1,0,2,0.475039,8,1389,0.000000,0.000000,0.000000,3,yes
3,3.105894,7,1,1,0,2.890612,1,0,2,0.475039,8,579,0.000000,0.000000,0.000000,3,yes
4,3.021951,0,1,2,0,2.179973,0,0,2,0.475039,8,673,0.367383,0.000000,0.000000,3,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11157,1.259146,1,2,0,0,2.123234,1,0,0,2.256435,0,257,0.000000,0.000000,0.000000,3,no
11158,1.762804,7,1,1,0,2.350192,0,0,2,1.781396,6,83,1.102149,0.000000,0.000000,3,no
11159,1.175203,9,2,1,0,2.131915,0,0,0,2.137675,1,156,0.367383,0.000000,0.000000,3,no
11160,2.098577,9,1,1,0,2.122924,0,1,0,0.831318,8,9,0.367383,1.590755,2.181592,0,no
11161,1.343089,9,1,1,0,2.122924,0,0,0,0.950078,5,628,0.000000,0.000000,0.000000,3,no

#2.3. Apply **Decision tree, Logistic Regression, Random forest, kNN, Na√ØveBayes, SVM** algorithms to the preproceed dataset in the previous steps. Then compare the obtained results using **accuracy, precision, recall, f1** measures.

In [47]:
#code
X = new_bank_data.drop(columns='deposit')
y = new_bank_data[['deposit']]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# print table
print('not using selection feature')
table_not_using = PrettyTable(['Algorithms', 'Accuracy', 'Precision', 'Recall', 'F1'])
for i in range(0, 6):
  table_not_using.add_row(getScore(i, X_train, X_test, y_train, y_test))
print(table_not_using)

not using selection feature
+---------------------------+--------------------+--------------------+--------------------+--------------------+
|         Algorithms        |      Accuracy      |     Precision      |       Recall       |         F1         |
+---------------------------+--------------------+--------------------+--------------------+--------------------+
|       Random forest       | 0.8374384236453202 | 0.8376145994114796 | 0.8383763095898562 | 0.8373694091276527 |
| Navie Bayes MultinomialNB | 0.7245857590685177 | 0.728295611178809  | 0.720532117615843  | 0.7206213446232586 |
|         SVM linear        | 0.7877295118674429 | 0.787231879188697  | 0.7873270296130126 | 0.7872769149141423 |
|       Decision tree       | 0.7702642185400806 | 0.7698670934117203 | 0.7692838362640808 | 0.7695068618011813 |
|    Logistic Regression    | 0.7836990595611285 | 0.7835817039895377 | 0.7824484807551599 | 0.7828208109944876 |
|          kNN k=5          | 0.741603224361845  | 0.7412197071217528 | 0.7402557670196428 | 0.7405540537139118 |
+---------------------------+--------------------+--------------------+--------------------+--------------------+

#2.4. Using a selection feature technique to above dataset, then compare the classification results with those in Task 2.3.

In [49]:
#code
new_X = SelectKBest(chi2, k=round(new_bank_data.shape[1] / 2)).fit_transform(X, y)
X_train, X_test, y_train, y_test = train_test_split(new_X, y, test_size=0.2)
print('using selection feature')
table_using = PrettyTable(['Algorithms', 'Accuracy', 'Precision', 'Recall', 'F1'])
for i in range(0,6):
  table_using.add_row(getScore(i, X_train, X_test, y_train, y_test))
print(table_using)

using selection feature
+---------------------------+--------------------+--------------------+--------------------+--------------------+
|         Algorithms        |      Accuracy      |     Precision      |       Recall       |         F1         |
+---------------------------+--------------------+--------------------+--------------------+--------------------+
|       Random forest       | 0.7832512315270936 | 0.7828923187054297 | 0.7834040565485569 | 0.783006442514492  |
| Navie Bayes MultinomialNB | 0.7281683833407971 | 0.7277032621027677 | 0.7268695691324119 | 0.7271262037608373 |
|         SVM linear        | 0.8060904612628751 | 0.806564197620022  | 0.8071591778848318 | 0.8060454956768455 |
|       Decision tree       | 0.7335423197492164 | 0.7329815694403508 | 0.7325930845076764 | 0.7327445661739487 |
|    Logistic Regression    | 0.8034034930586654 | 0.8035151833306413 | 0.8021447706091576 | 0.8025825119578827 |
|          kNN k=5          | 0.767577250335871  | 0.7680404098761866 | 0.7685606231146729 | 0.767523353940607  |
+---------------------------+--------------------+--------------------+--------------------+--------------------+

#Task 3.
For a given dataset (**mobile price classification**), perform feature selection techniques and then compare the performance of selected classification algorithms (**Decision Tree, kNN, Logistic Regression, SVM, Random Forest, and NaiveBayes**) based on **accuracy, precision, recall, and f1** measures.

In [53]:
# code
mobile_data = pd.read_csv('mobile.csv')

X = mobile_data.drop(columns='price_range')
y = mobile_data[['price_range']]

new_X = SelectKBest(chi2, k=round(new_bank_data.shape[1] / 2)).fit_transform(X, y)
X_train, X_test, y_train, y_test = train_test_split(new_X, y, test_size=0.2)
print('using selection feature')
table_using = PrettyTable(['Algorithms', 'Accuracy', 'Precision', 'Recall', 'F1'])
for i in range(0,6):
  table_using.add_row(getScore(i, X_train, X_test, y_train, y_test))
print(table_using)

using selection feature
+---------------------------+----------+--------------------+--------------------+--------------------+
|         Algorithms        | Accuracy |     Precision      |       Recall       |         F1         |
+---------------------------+----------+--------------------+--------------------+--------------------+
|       Random forest       |   0.9    | 0.9016441908807366 | 0.9014803017981387 | 0.9014578693150581 |
| Navie Bayes MultinomialNB |  0.5275  | 0.5171837720595485 | 0.5294221559591579 | 0.5183786826692698 |
|         SVM linear        |  0.9775  | 0.9776992439390654 | 0.9776969820186139 | 0.977686725844724  |
|       Decision tree       |  0.815   | 0.8154233836076354 | 0.8170581458389808 | 0.8161045672729211 |
|    Logistic Regression    |  0.9775  | 0.9776984380465696 | 0.9777460016264571 | 0.9777103280672752 |
|          kNN k=5          |   0.9    | 0.9032800764197644 | 0.9014120809614169 | 0.9019787331804812 |
+---------------------------+----------+--------------------+--------------------+--------------------+

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of f AND g EVALUATIONS EXCEEDS LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

#Task 4.
For a given dataset (named **mushroom.csv**) with the following information:

*   Attribute Information: (**classes**: edible=e, poisonous=p)
*   **cap-shape**: bell=b,conical=c,convex=x,flat=f, knobbed=k,sunken=s
*   **cap-surface**: fibrous=f,grooves=g,scaly=y,smooth=s
*   **cap-color**: brown=n,buff=b,cinnamon=c,gray=g,green=r,pink=p,purple=u,red=e,white=w,yellow=y
*   **bruises**: bruises=t,no=f
*   **odor**: almond=a,anise=l,creosote=c,fishy=y,foul=f,musty=m,none=n,pungent=p,spicy=s
*   **gill-attachment**: attached=a,descending=d,free=f,notched=n
*   **gill-spacing**: close=c,crowded=w,distant=d
*   **gill-size**: broad=b,narrow=n
*   **gill-color**: black=k,brown=n,buff=b,chocolate=h,gray=g, green=r,orange=o,pink=p,purple=u,red=e,white=w,yellow=y
*   **stalk-shape**: enlarging=e,tapering=t
*   **stalk-root**: bulbous=b,club=c,cup=u,equal=e,rhizomorphs=z,rooted=r,missing=?
*   **stalk-surface-above-ring**: fibrous=f,scaly=y,silky=k,smooth=s
*   **stalk-surface-below-ring**: fibrous=f,scaly=y,silky=k,smooth=s
*   **stalk-color-above-ring**: brown=n,buff=b,cinnamon=c,gray=g,orange=o,pink=p,red=e,white=w,yellow=y
*   **stalk-color-below-ring**: brown=n,buff=b,cinnamon=c,gray=g,orange=o,pink=p,red=e,white=w,yellow=y
*   **veil-type**: partial=p,universal=u
*   **veil-color**: brown=n,orange=o,white=w,yellow=y
*   **ring-number**: none=n,one=o,two=t
*   **ring-type**: cobwebby=c,evanescent=e,flaring=f,large=l,none=n,pendant=p,sheathing=s,zone=z
*   **spore-print-color**: black=k,brown=n,buff=b,chocolate=h,green=r,orange=o,purple=u,white=w,yellow=y
*   **population**: abundant=a,clustered=c,numerous=n,scattered=s,several=v,solitary=y
*   **habitat**: grasses=g,leaves=l,meadows=m,paths=p,urban=u,waste=w,woods=d

#Task 4.1. Apply approriate reprocessing techniques for the mushroom dataset

In [52]:
#code
mushroom_data = pd.read_csv('mushrooms.csv')
columns = mushroom_data.drop(columns='class').columns
mushroom_data = my_label_encoder(mushroom_data, columns);

#Task 4.2. Apply classification algorithms (**Decision Tree, Logistic Regression, SVM, kNN, Random Forest, NaiveBayes**) to the reprocessed dataset

In [55]:
#code

X = mushroom_data.drop(columns='class')
y = mushroom_data[['class']]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
print('using selection feature')
table_using = PrettyTable(['Algorithms', 'Accuracy', 'Precision', 'Recall', 'F1'])
for i in range(0,6):
  table_using.add_row(getScore(i, X_train, X_test, y_train, y_test))
print(table_using)

using selection feature
+---------------------------+--------------------+--------------------+--------------------+--------------------+
|         Algorithms        |      Accuracy      |     Precision      |       Recall       |         F1         |
+---------------------------+--------------------+--------------------+--------------------+--------------------+
|       Random forest       |        1.0         |        1.0         |        1.0         |        1.0         |
| Navie Bayes MultinomialNB | 0.8135384615384615 | 0.8276110617431294 | 0.8070869433044536 | 0.808793016474382  |
|         SVM linear        | 0.9704615384615385 | 0.9701951904063277 | 0.9705768353853169 | 0.970372666277713  |
|       Decision tree       |        1.0         |        1.0         |        1.0         |        1.0         |
|    Logistic Regression    | 0.9501538461538461 | 0.9500124657192719 | 0.9499468004255966 | 0.9499792696612348 |
|          kNN k=5          | 0.9981538461538462 |    0.998046875     | 0.9982558139534884 | 0.9981479096453446 |
+---------------------------+--------------------+--------------------+--------------------+--------------------+

#Task 4.3. Apply an feature selection method to dataset obtained in Task 4.1, then apply classification algorithm to the obtained dataset. Compare the performance of classification models before and after applying the feature selection technique in term of **accuracy, precision, recall, and F1** measures

In [57]:
#code
new_X = SelectKBest(chi2, k=round(mushroom_data.shape[1] / 2)).fit_transform(X, y)
X_train, X_test, y_train, y_test = train_test_split(new_X, y, test_size=0.2)
print('using selection feature')
table_using = PrettyTable(['Algorithms', 'Accuracy', 'Precision', 'Recall', 'F1'])
for i in range(0,6):
  table_using.add_row(getScore(i, X_train, X_test, y_train, y_test))
print(table_using)

using selection feature
+---------------------------+--------------------+--------------------+--------------------+--------------------+
|         Algorithms        |      Accuracy      |     Precision      |       Recall       |         F1         |
+---------------------------+--------------------+--------------------+--------------------+--------------------+
|       Random forest       |        1.0         |        1.0         |        1.0         |        1.0         |
| Navie Bayes MultinomialNB |       0.784        | 0.8005175709651393 | 0.7736235833470503 | 0.7756221506520973 |
|         SVM linear        | 0.9415384615384615 | 0.9421290273207317 | 0.9402597679706884 | 0.9410627001243457 |
|       Decision tree       |        1.0         |        1.0         |        1.0         |        1.0         |
|    Logistic Regression    | 0.9347692307692308 | 0.9356130268199234 | 0.9332069852649804 | 0.9342010769249575 |
|          kNN k=5          |        1.0         |        1.0         |        1.0         |        1.0         |
+---------------------------+--------------------+--------------------+--------------------+--------------------+

#Finally,
Save a copy in your Github. Remember renaming the notebook.